Lesson_19_django2/pizza_project_ETALON/pizza_app/urls.py
from django.conf.urls import url

from pizza_app.views import create, view, close, stats

urlpatterns = [
    url(r'^create/', create, name='create'),
    # view/<int:pizza_order_id>
    url(r'^view/(?P<pizza_order_id>[0-9]+)/', view, name='view'),
    url(r'^close/(?P<pizza_order_id>[0-9]+)/', close, name='close'),

    url(r'^stats/', stats, name='stats'),
]

Lesson_19_django2/pizza_project_ETALON/pizza_project/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

from pizza_app import urls as pizza_urls
from pizza_app.views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^pizza/', include(pizza_urls, namespace='pizza')),

    url(r'^$', index, name='index'),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

Lesson_19_django2/pizza_project_ETALON/pizza_app/models.py
from django.conf import settings
from django.db import models
from django.db.models import Manager
from django.utils import timezone
from django.db.models.signals import post_save, m2m_changed
from django.utils.text import get_valid_filename


class Address(models.Model):
    full = models.CharField(max_length=150)

    def __str__(self):
        return str(self.full)


class PizzaIngredient(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return str(self.name)


class PizzaMenuItem(models.Model):
    name = models.CharField(max_length=50)
    ingredients = models.ManyToManyField(
        'PizzaIngredient',
        related_name='ingredients'
    )

    def __str__(self):
        return str(self.name)


class PizzaSize(models.Model):
    LARGE = ('XL', 'Large')
    MEDIUM = ('MD', 'Medium')
    SMALL = ('SM', 'Small')
    __all = dict([LARGE, MEDIUM, SMALL])

    size = models.CharField(max_length=2, choices=__all.items())

    def __str__(self):
        return str(self.__all[self.size])


class PizzaOrderManager(Manager):
    def get_queryset(self, **kwargs):
        return super().get_queryset().filter(
            delivered=True,
        )


class PizzaOrderUndeliveredManager(Manager):
    def get_queryset(self, **kwargs):
        return super().get_queryset().filter(
            delivered=False,
        )


class PizzaOrder(models.Model):
    # Linking:
    kind = models.ForeignKey('PizzaMenuItem', related_name='pizzas')
    size = models.ForeignKey('PizzaSize', related_name='pizzas')
    delivery = models.ForeignKey('Address', related_name='pizzas')

    # Buisness logic:
    extra = models.ManyToManyField(
        'PizzaIngredient', blank=True, related_name='pizzas_extras')
    exclude = models.ManyToManyField('PizzaIngredient', blank=True)
    comment = models.CharField(max_length=140, blank=True)

    # Utils:
    delivered = models.BooleanField(default=False)
    date_created = models.DateTimeField(default=timezone.now)
    date_delivered = models.DateTimeField(default=None, null=True)

    objects = Manager()
    delivered_manager = PizzaOrderManager()
    undelivered_manager = PizzaOrderUndeliveredManager()



    def mark_delivered(self, commit=True):
        self.delivered = True
        self.date_delivered = timezone.now()
        if commit:
            self.save()

    def save(self, **kwargs):
        if not self.pk:
            print('Creating new PizzaOrder!')
        else:
            print('Updating the existing one')

        super(PizzaOrder, self).save(**kwargs)

    def __str__(self):
        return 'PizzaOrder [%s]' % self.id

Lesson_19_django2/pizza_project_ETALON/pizza_app/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.core.exceptions import ValidationError

from pizza_app.models import PizzaOrder, Address


class DeliveryForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = [
            'full',
        ]


class PizzaOrderForm(forms.ModelForm):
    class Meta:
        model = PizzaOrder
        exclude = [
            'delivered',
            'date_created',
            'date_delivered',
            'delivery',
        ]

    def clean(self):
        data = self.cleaned_data
        excluded = data['exclude']

        errors = []
        for item in excluded:
            if item in data['extra']:
                errors.append(str(item))

        if errors:
            raise ValidationError(
                'Ingredients [{}] are in extras and excludes!'.format(
                    ', '.join(errors)
                )
            )
        return data

    def save(self, commit=True, delivery=None):
        if delivery is None:
            raise ValueError('Delivery was not set')

        inst = super().save(commit=False)
        inst.delivery = delivery

        if commit:
            inst.save()

        return inst

Lesson_19_django2/pizza_project_ETALON/pizza_app/views.py
from django.core.urlresolvers import reverse
from django.db import transaction
from django.db.models import Avg, Count, F
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from pizza_app.models import PizzaOrder, PizzaSize
from pizza_app.forms import PizzaOrderForm, DeliveryForm


# Create your views here.


def index(request):
    if request.method == 'GET':
        pizzas = PizzaOrder.objects.all()
        return render(request, 'pizza_app/index.html', {'pizzas': pizzas})
    return HttpResponse(status=405)


def create(request):
    if request.method == 'GET':
        c = {
            'pizza_form': PizzaOrderForm(),
            'delivery_form': DeliveryForm(),
        }
        return render(request, 'pizza_app/create.html', c)

    elif request.method == 'POST':
        pizza_form = PizzaOrderForm(request.POST)
        delivery_from = DeliveryForm(request.POST)

        if pizza_form.is_valid() and delivery_from.is_valid():
            with transaction.atomic():
                delivery = delivery_from.save()
                pizza = pizza_form.save(delivery=delivery)
                pizza_form.save_m2m()

            return redirect(reverse('pizza:view', kwargs={
                'pizza_order_id': pizza.pk
            }))
        else:
            c = {
                'pizza_form': pizza_form,
                'delivery_form': delivery_from,
            }
            return render(request, 'pizza_app/create.html', c)
    return HttpResponse(status=405)


def view(request, pizza_order_id):
    if request.method == 'GET':
        # pizza = get_object_or_404(PizzaOrder, id=pizza_order_id)

        #pizza = PizzaOrder.objects.filter(id=pizza_order_id).first()
        #pizza = PizzaOrder.objects.select_related().filter(id=pizza_order_id).first()
        pizza = PizzaOrder.objects.select_related('kind').filter(id=pizza_order_id).first()
        # pizza = PizzaOrder.objects.select_related()\
        #     .prefetch_related()\
        #     .filter(id=pizza_order_id)\
        #     .first()
        # pizza = PizzaOrder.objects\
        #     .select_related()\
        #     .prefetch_related('extra', 'exclude')\
        #     .filter(id=pizza_order_id).first()

        if not pizza:
            raise Http404

        return render(request, 'pizza_app/view.html', {'pizza': pizza})
    return HttpResponse(status=405)


def close(request, pizza_order_id):
    if request.method == 'GET':
        try:
            pizza = get_object_or_404(PizzaOrder, id=pizza_order_id)
            pizza.mark_delivered()

            return redirect(reverse('pizza:view', kwargs={
                'pizza_order_id': pizza.pk
            }))
        except PizzaOrder.DoesNotExist:
            return HttpResponse('Does not exist', status_code=404)
    return HttpResponse(status=405)


def stats(request):
    if request.method == 'GET':
        count = PizzaOrder.objects.count()
        average_extras = PizzaOrder.objects.all().annotate(
            extra_count=Count('extra')
        ).aggregate(result=Avg('extra_count'))

        small_size = PizzaSize.objects.get(
            size=PizzaSize.SMALL[0]
        )
        small_pizzas = PizzaOrder.objects.filter(
            size=small_size
        )

        small_pizzas = PizzaOrder.objects.filter(
            size__size=PizzaSize.SMALL[0],
        )

        print(list(small_pizzas))
        print(repr(PizzaOrder.objects))
        s = PizzaOrder

        today = timezone.now()
        query = {
            'date_created__day': today.day,
            'date_created__month': today.month,
            'date_created__year': today.year,
        }
        today_pizzas = PizzaOrder.objects.filter(
            **query
        ).count()

        today_delivered = PizzaOrder.delivered_manager.filter(
            # delivered=True,  # TODO: manager
            **query
        ).count()

        # Try these lines with PostgreSQL:
        # average_delivery_time = PizzaOrder.objects.filter(
        #     delivered=True,
        # ).annotate(
        #     diff=F('date_delivered') - F('date_created')
        # ).aggregate(result=Avg('diff'))

        params = {
            'count': count,
            'average_extras': average_extras['result'],
            'today_pizzas': today_pizzas,
            'today_delivered': today_delivered,
            'average_delivery_time': 'not available with sqlite',
        }

        return render(request, 'pizza_app/stats.html', {'params': params})
    return HttpResponse(status=405)

Lesson_19_django2/pizza_project_ETALON/pizza_app/templates/pizza_app/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'pizza_app/tacit.min.css' %}" />
    <link rel="stylesheet" href="{% static 'pizza_app/styles.css' %}" />
</head>


<body>


  <main>
    {% block content %}
    {% endblock %}
  </main>

<nav>
    {% block nav %}<hr />
    <span><a href="{% url 'index' %}">Back to main</a></span>
    {% endblock %}
</nav>

</body>

</html>

Lesson_19_django2/pizza_project_ETALON/pizza_app/templates/pizza_app/create.html
{% extends 'pizza_app/_base.html' %}

{% block content %}

<form action="{% url 'pizza:create' %}" method="POST">
    {% csrf_token %}

    <h2>Address</h2>
    {{ delivery_form.as_p }}

    <hr />

    <h2>Pizza</h2>
    {{ pizza_form.as_p }}

    <input type="submit" value="Submit" />
</form>
{% endblock %}

Lesson_19_django2/pizza_project_ETALON/pizza_app/templates/pizza_app/index.html
{% extends 'pizza_app/_base.html' %}

{% block content %}
  <a href="{% url 'pizza:stats' %}">Pizza stats</a><br>
  <a href="{% url 'pizza:create' %}">Create new</a>

  <ul>
  {% for pizza in pizzas %}
      <li><a href="{% url 'pizza:view' pizza.id %}">{{ pizza }}</a></li>
  {% endfor %}
  </ul>

{% endblock %}
{% block nav %}
{% endblock %}

Lesson_19_django2/pizza_project_ETALON/pizza_app/templates/pizza_app/stats.html
{% extends 'pizza_app/_base.html' %}

{% block content %}

<p>Pizzas created: {{ params.count }}</p>
<p>Average extra ingredients on pizza: {{ params.average_extras }}</p>

<p>Today pizzas created: {{ params.today_pizzas }}</p>
<p>Today pizzas delivered: {{ params.today_delivered }}</p>

<p>Average delivery time: {{ params.average_delivery_time }}</p>

{% endblock %}

Lesson_19_django2/pizza_project_ETALON/pizza_app/templates/pizza_app/view.html
{% extends 'pizza_app/_base.html' %}

{% block content %}

<div>
    <p>Name: {{ pizza.kind }}</p>
    <p>Size: {{ pizza.size }}</p>

    <p>Delivery address: {{ pizza.delivery.full }}</p>

    <p>Ingredients:</p>
    <ul>
    {% for ingredient in pizza.kind.ingredients.all %}
        {% if ingredient not in pizza.exclude.all %}
        <li>{{ ingredient.name }}</li>
        {% endif %}
    {% endfor %}
    </ul>

    <p>Extra</p>
    <ul>
    {% for ingredient in pizza.extra.all %}
        <li>{{ ingredient.name }}</li>
    {% endfor %}
    </ul>

    <p>Excluded</p>
    <ul>
    {% for ingredient in pizza.exclude.all %}
        <li>{{ ingredient.name }}</li>
    {% endfor %}
    </ul>

    <p>Comment: {{ pizza.comment }}</p>

    <hr />

    <p>Status: {{ pizza.delivered|yesno:"Delivered,Delivering,WHAT?" }}</p>
    <p>Created: {{ pizza.date_created }}</p>
    <p>Delivered: {{ pizza.date_delivered|default_if_none:"Not yet" }}</p>

    {% if not pizza.delivered %}
        <a href="{% url 'pizza:close' pizza.id %}">Mark delivered</a><br>
    {% endif %}
</div>

{% endblock %}